---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    expose.service-key.config.fabric8.io/keycloak: keycloak.url
  labels:
    app: auth
    provider: fabric8
    version: 4.0-SNAPSHOT
    group: io.fabric8.platform.apps
  name: auth
data:
  db.host: auth-db
  db.port: "5432"
  auth_notapproved_redirect: ""
  chestarter.url: http://che-starter:10000
  keycloak.url: http://keycloak
  wit.url: http://wit
  openshift.tenant.masterurl: http://kubernetes.default/
  postgres.connection.maxidle: "90"
  postgres.connection.maxopen: "90"
  postgres.sslmode: disable
  redirect.valid: .*
  tenant.serviceurl: http://kubernetes.default/
