---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: configmapcontroller
    provider: fabric8
    version: 4.0-SNAPSHOT
    group: io.fabric8.platform.apps
  name: configmapcontroller
