---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/target-platform: kubernetes
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/fabric8-docker-registry/src/main/fabric8/icon.png
    fabric8.io/git-commit: 7452018a668f222a9f7ba0f2dfaae64416ccbc39
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=docker-registry&var-version=1.0.1
    fabric8.io/scm-con-url: scm:git:git@github.com:fabric8-apps/docker-registry.git
    fabric8.io/scm-url: http://github.com/fabric8-apps/docker-registry
    fabric8.io/git-branch: release-v1.0.1
    fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8-apps/docker-registry.git
    fabric8.io/scm-tag: docker-registry-1.0.0
  labels:
    provider: fabric8
    project: docker-registry
    version: 1.0.1
    group: io.fabric8.apps
  name: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      project: docker-registry
      provider: fabric8
      group: io.fabric8.apps
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 7452018a668f222a9f7ba0f2dfaae64416ccbc39
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=docker-registry&var-version=1.0.1
        fabric8.io/scm-con-url: scm:git:git@github.com:fabric8-apps/docker-registry.git
        pod.alpha.kubernetes.io/init-containers: '[{"image":"busybox","imagePullPolicy":"IfNotPresent","name":"fmp-volume-permission","command":["chmod","777","/var/lib/registry"],"volumeMounts":[{"mountPath":"/var/lib/registry","name":"fabric8-docker-registry-storage"}]}]'
        fabric8.io/scm-url: http://github.com/fabric8-apps/docker-registry
        fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/fabric8-docker-registry/src/main/fabric8/icon.png
        fabric8.io/target-platform: kubernetes
        fabric8.io/git-branch: release-v1.0.1
        fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8-apps/docker-registry.git
        fabric8.io/scm-tag: docker-registry-1.0.0
        maven.fabric8.io/source-url: jar:file:/home/concaf/.m2/repository/io/fabric8/apps/docker-registry/1.0.1/docker-registry-1.0.1.jar!/META-INF/fabric8/kubernetes.yml
      labels:
        provider: fabric8
        project: docker-registry
        version: 1.0.1
        group: io.fabric8.apps
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: registry:2
        imagePullPolicy: IfNotPresent
        name: fabric8-docker-registry
        ports:
        - containerPort: 5000
          name: http
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
        volumeMounts:
        - mountPath: /var/lib/registry
          name: fabric8-docker-registry-storage
          readOnly: false
      volumes:
      - name: fabric8-docker-registry-storage
        persistentVolumeClaim:
          claimName: fabric8-docker-registry-storage
