---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/target-platform: kubernetes
    expose.service-key.config.fabric8.io/keycloak: keycloak.url
    expose.service-key.config.fabric8.io/wit: wit.url
  labels:
    app: init-tenant
    provider: fabric8
    version: 4.0-SNAPSHOT
    group: io.fabric8.platform.apps
  name: f8tenant
data:
  keycloak.url: http://keycloak
  wit.url: http://wit
  openshift.tenant.masterurl: https://kubernetes.default:443
  openshift.use.current.cluster: "true"
  api.server.insecure.skip.tls.verify: "true"
  postgres.connection.maxidle: "90"
  postgres.connection.maxopen: "90"
  template.domain: d800.free-int.openshiftapps.com
  template.recommender.external.name: recommender.api.prod-preview.openshift.io
  keycloak.skip.host.verify: "true"
  disable.oso.quotas: "true"
  kubernetes.mode: "true"
  tenant.exposer: Ingress
