---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: init-tenant
    provider: fabric8
    version: 4.0-SNAPSHOT
    group: io.fabric8.platform.apps
  name: f8tenant
data:
  postgres.database: cG9zdGdyZXM=
  postgres.host: aW5pdC10ZW5hbnQtZGI=
  postgres.port: NTQzMg==
  postgres.user: cG9zdGdyZXM=
  postgres.password: bXlzZWNyZXRwYXNzd29yZA==
  template.recommender.api.token: Zm9v
type: Opaque
