---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/target-platform: kubernetes
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/fabric8-docker-registry/src/main/fabric8/icon.png
    expose: "true"
    fabric8.io/git-commit: 7452018a668f222a9f7ba0f2dfaae64416ccbc39
    fabric8.io/git-branch: release-v1.0.1
    fabric8.io/scm-con-url: scm:git:git@github.com:fabric8-apps/docker-registry.git
    fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8-apps/docker-registry.git
    fabric8.io/scm-tag: docker-registry-1.0.0
    fabric8.io/scm-url: http://github.com/fabric8-apps/docker-registry
  labels:
    expose: "true"
    provider: fabric8
    project: docker-registry
    version: 1.0.1
    group: io.fabric8.apps
  name: fabric8-docker-registry
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    project: docker-registry
    provider: fabric8
    group: io.fabric8.apps
