---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 2ebbe3448c2a1fd5c903badd7a8b264253f39124
    fabric8.io/git-branch: master
    fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/forge
    fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/forge
    fabric8.io/scm-tag: app-console-2.0.1
    fabric8.io/scm-url: http://github.com/fabric8io/fabric8-platform/apps/forge
  labels:
    expose: "true"
    app: forge
    provider: fabric8
    version: 4.0-SNAPSHOT
    group: io.fabric8.platform.apps
  name: forge
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: forge
    provider: fabric8
    group: io.fabric8.platform.apps
