---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/target-platform: kubernetes
    expose.config.fabric8.io/apiserver-url-key: apiserver.url
  labels:
    app: forge
    provider: fabric8
    version: 4.0-SNAPSHOT
    group: io.fabric8.platform.apps
  name: forge
data:
  keycloak.url: http://f8tenant
  apiserver.url: http://kubernetes
