---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.fabric8.io/update-on-change: forge
    fabric8.io/git-commit: 2ebbe3448c2a1fd5c903badd7a8b264253f39124
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=forge&var-version=4.0-SNAPSHOT
    fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/forge
    fabric8.io/scm-url: http://github.com/fabric8io/fabric8-platform/apps/forge
    fabric8.io/git-branch: master
    fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/forge
    fabric8.io/scm-tag: app-console-2.0.1
  labels:
    app: forge
    provider: fabric8
    version: 4.0-SNAPSHOT
    group: io.fabric8.platform.apps
  name: forge
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: forge
      provider: fabric8
      group: io.fabric8.platform.apps
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 2ebbe3448c2a1fd5c903badd7a8b264253f39124
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=forge&var-version=4.0-SNAPSHOT
        fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/forge
        fabric8.io/scm-url: http://github.com/fabric8io/fabric8-platform/apps/forge
        configmap.fabric8.io/update-on-change: forge
        fabric8.io/git-branch: master
        fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/forge
        fabric8.io/scm-tag: app-console-2.0.1
        maven.fabric8.io/source-url: jar:file:/home/concaf/fabric8/src/github.com/fabric8io/fabric8-platform/apps/forge/target/forge-4.0-SNAPSHOT.jar!/META-INF/fabric8/kubernetes.yml
      labels:
        app: forge
        provider: fabric8
        version: 4.0-SNAPSHOT
        group: io.fabric8.platform.apps
    spec:
      containers:
      - env:
        - name: LAUNCHPAD_BACKEND_CATALOG_GIT_REF
          value: next
        - name: OPENSHIFT_API_URL
          valueFrom:
            configMapKeyRef:
              key: apiserver.url
              name: forge
        - name: KEYCLOAK_SAAS_URL
          valueFrom:
            configMapKeyRef:
              key: keycloak.url
              name: forge
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: fabric8/generator-backend:1.0.66
        livenessProbe:
          failureThreshold: 30
          httpGet:
            path: forge/version
            port: 8080
          initialDelaySeconds: 300
          timeoutSeconds: 10
        name: forge
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          httpGet:
            path: forge/version
            port: 8080
          initialDelaySeconds: 3
          timeoutSeconds: 3
        workingDir: /home
