---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/target-platform: kubernetes
    expose-full.service-key.config.fabric8.io/f8tenant: keycloak.url
  labels:
    app: fabric8
    provider: fabric8
    version: 4.0-SNAPSHOT
    group: io.fabric8.platform.apps
  name: sso
data:
  keycloak.url: http://init-tenant
