---
apiVersion: v1
kind: Service
metadata:
  annotations:
    api.service.kubernetes.io/path: /api/
    service.alpha.openshift.io/dependencies: '[{"name":"wit-db","namespace":"","kind":"Service"}]'
    fabric8.io/git-commit: 2ebbe3448c2a1fd5c903badd7a8b264253f39124
    fabric8.io/git-branch: master
    fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/wit
    fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/wit
    fabric8.io/scm-tag: app-console-2.0.1
    fabric8.io/scm-url: http://github.com/fabric8io/fabric8-platform/apps/wit
  labels:
    service: wit
    expose: "true"
    app: wit
    provider: fabric8
    version: 4.0-SNAPSHOT
    group: io.fabric8.platform.apps
  name: wit
spec:
  ports:
  - name: "8080"
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    service: wit
    app: wit
    provider: fabric8
    group: io.fabric8.platform.apps
  type: ClusterIP
