---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: wit
    provider: fabric8
    version: 4.0-SNAPSHOT
    group: io.fabric8.platform.apps
  name: wit-postgresql-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
